document.writeln('<script type="text/javascript" src="/top_bar/js/jQueryRotate.2.2.js"></script>');
document.writeln('<script type="text/javascript" src="/top_bar/js/shareToSociality.js"></script>');
document.writeln('<script type="text/javascript" src="/js/appAD-page.js"></script>');
document.writeln('<link href="css/top_bar_test2.css" rel="stylesheet" type="text/css" />');
document.writeln('<link href="/css/old_browser.css" rel="stylesheet" type="text/css" />');
document.writeln('<link href="/css/appAD-page.css" rel="stylesheet" type="text/css" />');
document.writeln('<!--[if lte IE 9]>');
document.writeln('<div id="browser" class="fixed">');
document.writeln('<div id="browser_cont">');
document.writeln('<div class="note">');
document.writeln('<h2>請更新瀏覽器版本</h2><p>為體驗更安全、流暢的網站服務，請更新您的瀏覽器</p>');
document.writeln('</div>');
document.writeln('<ul id="browser_all">');
document.writeln('<li><a href="http://windows.microsoft.com/zh-tw/internet-explorer/download-ie" target="_blank"><img src="/images/old_browser/old_browser_ie.png" alt="下載 IE11 瀏覽器" title="下載 IE11 瀏覽器" /></a></li>');
document.writeln('<li><a href="https://www.google.com/intl/zh-TW/chrome/browser/desktop/index.html?hl=zh_TW" target="_blank"><img src="/images/old_browser/old_browser_chrome.png" alt="下載 Chrome 瀏覽器" title="下載 Chrome 瀏覽器" /></a></li>');
document.writeln('<li><a href="http://mozilla.com.tw/firefox/new/" target="_blank"><img src="/images/old_browser/old_browser_ff.png" alt="下載 Firefox 瀏覽器" title="下載 Firefox 瀏覽器" /></a></li>');
document.writeln('<li><a href="http://www.apple.com/tw/safari/" target="_blank"><img src="/images/old_browser/old_browser_safari.png" alt="下載 Safari 瀏覽器" title="下載Safari 瀏覽器" /></a></li>');
document.writeln('<li><a href="http://www.opera.com/zh-tw/o/ie-simple" target="_blank"><img src="/images/old_browser/old_browser_opera.png" alt="下載 Opera 瀏覽器" title="下載 Opera 瀏覽器" /></a></li>');
document.writeln('</ul>');
document.writeln('<a href="#" class="cancel_browser"><span>關閉</span></a>');
document.writeln('</div>');
document.writeln('<script language="javascript">');
document.writeln('$("body").addClass("non")');
document.writeln('$(".cancel_browser").on("click",function(){');
document.writeln('$("body").removeClass("non")');
document.writeln('})</script>');
document.writeln('</div>');
document.writeln('<![endif]-->');
document.writeln('<div class="top_bar_bg ">');
document.writeln('<div class="top_bar">');
document.writeln('<a class="top_bar_logo" href="http://www.eztravel.com.tw/" target="_blank">LOGO</a>');
// document.writeln('<div class="top_bar_recommend_btn"><div class="top_bar_recommend_btn_rotate"><img src="/top_bar/img/+.gif" id="rotate_img"/></div>分享</div>');
// document.writeln('<a class="top_bar_join" href="http://www.eztravel.com.tw/ezec/member/ec_join.jsp" target="_blank">加入會員</a>');
// document.writeln('<div class="top_bar_us_btn"><div class="top_bar_us_btn_rotate"></div>聯絡我們</div>');
// document.writeln('<div id="app_header">APP更低價<div id="pop_qr">APP訂購更低價</div></div>');
document.writeln('</div>');
document.writeln('</div>');
document.writeln('<div class="top_bar_recommend">');
document.writeln('<div class="top_bar_recommend_box box-shadow border-radius-bottom">');
document.writeln('<span>分享到</span>');
document.writeln('<a href="javascript:google();" class="google border-radius-3px"></a>');
document.writeln('<a href="javascript:twitter();" class="twitter border-radius-3px"></a>');
document.writeln('<a href="javascript:plurk();" class="plurk border-radius-3px"></a>');
document.writeln('<a href="javascript:facebook();" class="fb border-radius-3px"></a>');
document.writeln('</div>');
document.writeln('<div class="top_bar_us">');
document.writeln('<div class="top_bar_us_box box-shadow border-radius-bottom"><span><a href="http://www.eztravel.com.tw/service/quality/servicemail.htm" target="_blank"><img src="/top_bar/img/email.gif"/>服務信箱</a><br><a href="http://www.eztravel.com.tw/event/2009_55678/index.html" target="_blank"><img src="/top_bar/img/phone.gif"/>手機直撥 55678 </a><br><a><img src="/top_bar/img/call.gif"/>訂購諮詢 412-8001 </a></span></div>');
document.writeln('</div>');
document.writeln('</div>');
// document.write('<div id="app_footer">');
// document.write('    <ul>');
// document.write('		<li id="app_footer_mobile" title="APP訂購更低價"><img src="/images/appAD/app_ad.png"></li>');
// document.write('		<li id="app_footer_x" title="關閉廣告"><span>X</span></li>');
// document.write('    </ul>');
// document.write('</div>');
// document.write('<div id="app_footer_close" title="開啟廣告"><span>手機易遊網 旅行更低價</span></div>');